-- Migration created with Drizzle Kit
-- This file was generated by drizzle-kit when converting from Prisma

CREATE TABLE IF NOT EXISTS "change_me_if_needed" (
	"id" serial PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
